### PR TITLE
feat!: Implement Matchmaking Rewrite

### LINKED ISSUE #9: [Enhancement]: Port to matchmaking rewrite
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

Dani has been hard at work at a [complete rewrite of the matchmaking code in nex-protocols-common-go](https://github.com/PretendoNetwork/nex-protocols-common-go/pull/35). It uses a Postgres database for room state, eliminating race conditions and state inconsistencies (we hope) - it also correctly implements more NEX notification types, including those needed for Splatfest matchmaking. We also expect to see moderation improvements from examining the database.

It'd be nice to bring these improvements to Splatoon.

### Any other details to share? (OPTIONAL)

Some experimental work has happened in Minecraft: https://github.com/PretendoNetwork/minecraft-wiiu/tree/work/mm-rewrite

External contributors please note that the matchmaking rewrite is **not final** and **may not be merged** in its current state. Consider this experimental work to see if the improvements stick, which may be dropped from no fault of your own. Don't expect a merge into the main Splatoon branch until the matchmaking-rewrite also merges, but we'd love to experiment with such a build in the meantime.

### PR DESCRIPTION
**Pull request by ssdrive-flaktra**
Resolves #9 

### Changes:
Implements the nex-protocols-common-go matchmaking rewrite.

- [x] I have read and agreed to the [Code of Conduct](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CODE_OF_CONDUCT.md).
- [x] I have read and complied with the [contributing guidelines](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CONTRIBUTING.md).
- [x] What I'm implementing was an [approved issue](../issues?q=is%3Aopen+is%3Aissue+label%3Aapproved).
- [x] I have tested all of my changes.

### CODE REVIEW

**Comment by ssdrive-flaktra** [comment]
NOTE: For this PR to function with the rewrite, some changes need to be applied to it.
1. In `matchmake-extension/database/find_matchmake_session_by_search_criteria.go`, line 77, right after the `for` loop but before the `if` statement, add `if i == 1 { continue; }`.
2. Replace all instances of `ms.max_participants` and `ms.min_participants` with `g.max_participants` and `g.min_participants`.

**Comment by ssdrive-flaktra** [comment]
Reverted to draft due to Splatfest issues.

**Comment by ssdrive-flaktra** [comment]
Splatfests are secondary, it seems to work fine with private and regular battles. And the rewrite was also updated.

**Comment by shutterbug2000** [comment]
The matchmaking rewrite has a proper release now, so if you update nex-go, nex-protocols-go and nex-protocols-common-go to their latest releases, this will be ready to merge!

Thanks for your contribution!

**Comment by ssdrive-flaktra** [comment]
> The matchmaking rewrite has a proper release now, so if you update nex-go, nex-protocols-go and nex-protocols-common-go to their latest releases, this will be ready to merge!
> 
> Thanks for your contribution!

Alright, I'll just update and remove the overrides for the libraries!

**Comment by ssdrive-flaktra** [comment]
alright, ready to merge!

**Comment by ashquarky** [comment]
Worked good for me. I wasn't able to actually start a match, but that's cuz my test setup is incomplete - but matchmaking seemed to work well.

**Comment by MatthewL246** [comment]
Hey, I think you accidentally included the compiled server in this PR.

**Comment by ssdrive-flaktra** [comment]
> Hey, I think you accidentally included the compiled server in this PR.

Yeah, I noticed that lmao. my bad

**Pull request merged**
